antora:
  extensions:
  - '@springio/antora-extensions/partial-build-extension'
  - require: '@springio/antora-extensions/latest-version-extension'
  - require: '@springio/antora-extensions/inject-collector-cache-config-extension'
  - '@antora/collector-extension'
  - '@antora/atlas-extension'
  - require: '@springio/antora-extensions/root-component-extension'
    root_component_name: 'security'
  - '@springio/antora-extensions/static-page-extension'
site:
  title: Spring Security
  url: https://docs.spring.io/spring-security/reference
  robots: allow
git:
  ensure_git_suffix: false
content:
  sources:
  - url: https://github.com/spring-projects/spring-security
    branches: [main, '5.{{6..9},{1..9}+({0..9})}.x', '6.+({0..9}).x']
    tags: ['5.{{6..9},{1..9}+({0..9})}.+({0..9})?(-RC+({0..9}))', '6.+({0..9}).+({0..9})?(-{RC,M}*)','!(5.6.{0..10}*)', '!(5.7.{0..8}*)', '!(5.8.{0..3}*)','!(6.0.{0..3}*)','!(6.1.0*)']
    start_path: docs
asciidoc:
  attributes:
    page-stackoverflow-url: https://stackoverflow.com/tags/spring-security
    page-related-doc-categories: security
    page-related-doc-projects: framework,graphql
    hide-uri-scheme: '@'
    tabs-sync-option: '@'
  extensions:
  - '@asciidoctor/tabs'
  - '@springio/asciidoctor-extensions'
urls:
  latest_version_segment_strategy: redirect:to
  latest_version_segment: ''
  redirect_facility: httpd
ui:
  bundle:
    url: https://github.com/spring-io/antora-ui-spring/releases/download/v0.4.16/ui-bundle.zip
    snapshot: true
runtime:
  log:
    failure_level: warn
